sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.12'

branches:
  only:
    - master
    - travis-ci

# Not using `npm install --dev` because it is recursive. It will pull in the all
# development dependencies for CoffeeScript. Way too much spew in the Travis CI
# build output.

before_install:
  - npm install
  - npm install istanbul coveralls

env:
  global:
  - secure: "CvK1Xm8NH2c3WW6Egv48WctBySaTwX8HRsWyfcDLzxqdjbSFzugVo/vVzT1DMHGlKKye6Tw3740NIAJxEunFI8CF4dL6j2NHdl0ep8fp70C0bGKNQvQc6uMbi6EOQXLRmSdb8jTSRCuRw2uohg/Xo5oSbWiX/nR4XvHLbECW791lCYehK4ka+wq1aEts1XtrExEUv4FGyADV+jT3UWnXo0mnkKISzcXfg7xylcCIpSWszre+b9B3qXVBi38KbddCIUD1gqZZt+jqKZjp3q9u3LG5wTD5VCnhZsvkv25AGIo7wJLd41yVjXokXS4S71ZIjD4vDwp2k4wNnBqzoPWbxhnkaadG5J0zTKn9zRRmNxHQC5lRUhO4RMcN7fDbn3lp0ZUPMRj7VXiVXH48mm9Tthlu8ubC4ygkruLt4sW1Uun/hwUbPRoDxLjjAJjq5izPBbXnhwPlr3y0A/jB0cO7pluBHEu/lDNIOvK6vDrpsao3/9niqQ0PWF2+w0w1PMWTG03EFF2gXoSuUalJnYy8FAKUHECqG1fo9mGPesdeMObIqZ5agIuRvwj5nasNy8EWibZbQg/NyggeXf+AK+sjD71FJZIgeB8Ao0HI8MLvFkBGkp1yc1DAxlaquvhuLJ1LprdpIkjQ8FUwayWCIL1gCxgA7TqECDwT8K+KyQg479M="
