#!/bin/sh

set -e

t/sizes hotspot.js | sed 's/^/    /'

echo ""

(proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1

if [ "$TRAVIS" = "true" ] || [ "$MINIFY" = "true" ]; then
  # note: do not `--lift-vars` because it ruins arity functions by eliminating
  # unused function vars.
  echo ""
  echo "minified"
  echo ""
  bak=hotspot-$(date +'%FT%T' | tr ':' '-').js
  mv hotspot.js $bak
  cat $bak | uglifyjs > hotspot.js
  (proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1
  cp $bak hotspot.js
fi

if [ "$TRAVIS" = "true" ]; then
  echo ""
  echo "running with coverage"
  t/cover
  node_modules/.bin/istanbul report --format text
  echo ""

  echo "submitting to coveralls.io"
  (cat coverage/lcov.info | node_modules/.bin/coveralls) > /dev/null 2>&1
fi

echo ""
